var stats = {};
stats['db_overview'] =db.stats();
stats['nodes'] = db.pvd.count({'datatype' : 'node'});
stats['ways'] = db.pvd.count({'datatype' : 'way'});
stats['relations'] = db.pvd.count({'datatype' : 'relation'});
stats['distinct_users'] = db.pvd.distinct('created.user').length;
stats['top_3_users'] = db.pvd.aggregate([ {'$group' : { '_id': '$created.user', 'count' : { '$sum' : 1} } }, {$sort : {count : -1 } }, {$limit: 3} ]).toArray();
stats['users_with_1_data'] = db.pvd.aggregate([ {'$group' : { '_id': '$created.user', 'count' : { '$sum' : 1} } }, {$sort : {count : -1 } }, {$match: { 'count': 1 } } ]).toArray().length;
stats['average_user'] = db.pvd.aggregate([ {'$group' : { '_id': '$created.user', 'count' : { '$sum' : 1} } }, { '$group': { '_id' : 1, 'avg_docs' : { $avg : '$count' } } }   ])._batch;
printjson(stats);